#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jdiff
Version  : 1
Release  : 1
URL      : https://sourceforge.net/projects/javadiff/files/javadiff/javadiff%201.0.10/jdiff-1.0.10.tar.gz/download
Source0  : https://sourceforge.net/projects/javadiff/files/javadiff/javadiff%201.0.10/jdiff-1.0.10.tar.gz/download
Source1  : https://repo1.maven.org/maven2/jdiff/jdiff/1.0.9/jdiff-1.0.9.jar
Source2  : https://repo1.maven.org/maven2/jdiff/jdiff/1.0.9/jdiff-1.0.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: mvn-jdiff-data = %{version}-%{release}

%description
JDiff Doclet
Matthew Doar
doar@pobox.com
The JDiff doclet is used to generate a report describing the
difference between two public Java APIs. For more information on
the doclet and instructions for using it, see:

%package data
Summary: data components for the mvn-jdiff package.
Group: Data

%description data
data components for the mvn-jdiff package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9/jdiff-1.0.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9/jdiff-1.0.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9/jdiff-1.0.9.jar
/usr/share/java/.m2/repository/jdiff/jdiff/1.0.9/jdiff-1.0.9.pom
